drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title text NOT NULL,
    url text NOT NULL,
    rating INTEGER,
    description text
);

insert into bookmarks (title, url, rating, description)
values
    ('Facebook', 'www.facebook.com', 3),
    ('Amazon', 'www.amazon.com', 5),
    ('ESPN', 'www.ESPN.com', 4, 'Sports News'),
    ('Twitter', 'www.twitter.com', 5),
    ('Bloc', 'www.bloc.thinkful.com', 4),
    ('Netflix', 'www.netflix.com', 4, 'Video streaming'),
    ('HBO', 'www.hbogo.com', 5),
    ('Soundcloud', 'www.soundcloud.com', 2),
    ('GMail', 'www.mail.google.com', 5, 'Email service'),
    ('Google', 'www.google.com', 3, 'Search Engine')